### ISSUE TITLE
BadStatusLine exception when using an NTLM Squid proxy

### ISSUE THREAD

**Issue by Maartincm** [dopstar/requests-ntlm2#19]
#### Issue description
Hello there. I'm trying to test the **HTTP CONNECT Usage** example in the Readme section and it's failing with a `BadStatusLine` exception.
I believe this particular error might arise only when using Squid with NTLM Auth, because of how this proxy crafts the responses.

This might be related to #14 but no way to know because the proxy used for testing is not specified there.

#### Environment
Python 3.8 virtualenv with the following
<details>
  <summary>Dependencies</summary>

```
certifi==2020.6.20
cffi==1.14.3
chardet==3.0.4
cryptography==3.1.1
idna==2.10
ntlm-auth==1.5.0
pycparser==2.20
requests==2.24.0
requests-ntlm2==6.2.7
six==1.15.0
urllib3==1.25.11
```
</details>

Going through a **Squid 3.5.20** proxy with NTLMv2 auth.

#### Steps to reproduce the issue

1. Copy the code from [here](https://github.com/dopstar/requests-ntlm2#http-connect-usage) to a `ntlm_proxy.py` file.
2. Fill the missing connectivity and credentials fields and set a real url (github.com in my case) in the `get` call.
3. Run `python ntlm_proxy.py` using the python3.8 virtualenv.

#### What's the expected result?

The script should not fail. We should be able to see the response from the requested page with it's content.

#### What's the actual result?

A `BadStatusLine` exception is raised when trying to interpret the status of the second response of the Squid Proxy.
<details>
  <summary>The exception trace</summary>

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/connection.py", line 317, in connect
    self._tunnel()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests_ntlm2/connection.py", line 166, in _tunnel
    version, code, message, response = self._get_response()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests_ntlm2/connection.py", line 85, in _get_response
    version, code, message = response._read_status()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: icense


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/urllib3/connection.py", line 317, in connect
    self._tunnel()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests_ntlm2/connection.py", line 166, in _tunnel
    version, code, message, response = self._get_response()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests_ntlm2/connection.py", line 85, in _get_response
    version, code, message = response._read_status()
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('icense\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python_ntlm_auth.py", line 51, in <module>
    response = ntlm_request()
  File "python_ntlm_auth.py", line 46, in ntlm_request
    response = session.get('https://github.com', proxies=proxies)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/miniconda3/envs/ntlmproxy3.8/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('icense\n'))
```
</details>

#### Additional details / screenshot

Using wireshark and debugging I realized the issue was related to Squid sending an HTML page in the **407 Proxy Authentication Required** which splitted the request into multiple tcp packages. In addition, before this HTML page Squid is sending a blank line (`\r\n`) which is interpreted as the end of the request [here](https://github.com/dopstar/requests-ntlm2/blob/master/requests_ntlm2/connection.py#L158).
This two things (multiple TCP packages over the same socket and the blank line mid request) lead to the failure [here](https://github.com/dopstar/requests-ntlm2/blob/master/requests_ntlm2/connection.py#L166) because a header line is expected but garbage from the previous request is read instead.

I was able to fix this issue interpreting two consecutive new lines or empty lines as the requests actually finishing. I will create a PR with that so We can work from there.

Thanks!

**Comment by dopstar** [comment]
hey @Maartincm 

> Using wireshark and debugging I realized the issue was related to Squid sending an HTML page in the 407 Proxy Authentication Required which splitted the request into multiple tcp packages. In addition, before this HTML page Squid is sending a blank line (\r\n) which is interpreted as the end of the request here.

is it possible for you to share the wireshark pcap file **if it doesnt contain sensitive information**? alternatively would you share the screenshot showing what is described in the quoted section above (with sensitive parts being redacted/blanked out)?

i just want to be sure we wont break this hack:
https://github.com/dopstar/requests-ntlm2/blob/9ed2b2115fe5aeca536167d00fcdd76dc72f9c31/requests_ntlm2/connection.py#L65-L81

**Comment by Maartincm** [comment]
I don't think I can share the pcap but hope this images have relevant information. Feel free to ask for more info if you need.

**First image**: The 407 response from the Squid proxy, containing the Squid version. As can be seen, this response is split into 4 tcp packages, the first 3 each with content-length=1360 and the last one is tagged as the 407 response by wireshark.
![WireShark1](https://user-images.githubusercontent.com/28577666/96626686-32dc2b80-12e6-11eb-9dce-e4efa53d2578.png)

**Second image**: The same tcp package but showing the blank line after the header `Connection: keep-alive` and before the HTML page. This blank line is the one that makes the _tunnel method hit [this line](https://github.com/dopstar/requests-ntlm2/blob/master/requests_ntlm2/connection.py#L158)
![WireShark3](https://user-images.githubusercontent.com/28577666/96626700-353e8580-12e6-11eb-9834-645fe7dc6c21.png)

**Third image**: The next tcp package for the same response which begins with `icense` (continuation of the HTML page started in the previous image). `icense` is what `requests-ntlm2` is trying to interpret as the `200 Connection established` header from the next expected response of the proxy, throwing then the `BadStatusLine` exception.
![WireShark2](https://user-images.githubusercontent.com/28577666/96626694-34a5ef00-12e6-11eb-89f2-a8883a753eb3.png)
