### ISSUE TITLE
not able to connect to https url

### ISSUE THREAD

**Issue by punnojoy** [dopstar/requests-ntlm2#31]
Hello,  I am trying to connect to a https url via a squid proxy which is enabled for NTLM authentication. But it is throwing error. 

```python
from requests_ntlm2 import HttpNtlmAuth, NtlmCompatibility, HttpNtlmAdapter
import requests
import logging

logging.basicConfig(level=logging.DEBUG)

session = requests.Session()
proxi = {"https": 'http://{}:{}'.format('ip', 8080)}

ntlm_compatibility = NtlmCompatibility.NTLMv2_DEFAULT 

session.mount(
    'https://',
    HttpNtlmAdapter(
        "domain\\Administrator",
        "pwd",
        ntlm_compatibility=ntlm_compatibility
    )
)

session.auth = HttpNtlmAuth(
    "domain\\Administrator",
    "pwd",
    ntlm_compatibility=ntlm_compatibility
)

session.proxies = proxi

response = session.get('https://github.com')
print(response)
```

Output:
```python
DEBUG:requests_ntlm2.adapters:proxy headers: {}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): github.com:443
DEBUG:requests_ntlm2.connection:attempting to open tunnel using HTTP CONNECT
DEBUG:requests_ntlm2.connection:username: Administrator, domain: domain
DEBUG:requests_ntlm2.connection:workstation: workstation
DEBUG:requests_ntlm2.connection:> 'CONNECT github.com:443 HTTP/1.0\r\n'
DEBUG:requests_ntlm2.connection:> 'Host: github.com:443\r\n'
DEBUG:requests_ntlm2.connection:> 'Proxy-Authorization: NTLM TlRMTVNTUAABAAAAMbCI4g4ADgAoAAAADwAPADYAAAAGAbEdAAAAD2F1dGhtaW5kLmxvY2FsRUMyQU1BWi1BMkJLNjBH\r\n'
DEBUG:requests_ntlm2.connection:> 'Proxy-Connection: Keep-Alive\r\n'
DEBUG:requests_ntlm2.connection:< 'HTTP/1.1 407 Proxy Authentication Required\r\n'
INFO:requests_ntlm2.connection:< b'Content-Type: text/html; charset=utf-8\r\n'
INFO:requests_ntlm2.connection:< b'Content-Length: 6585\r\n'
INFO:requests_ntlm2.connection:< b'Connection: close\r\n'
INFO:requests_ntlm2.connection:< b'Proxy-Authenticate: Negotiate\r\n'
DEBUG:requests_ntlm2.connection:> 'CONNECT github.com:443 HTTP/1.0\r\n'
DEBUG:requests_ntlm2.connection:> 'Host: github.com:443\r\n'
DEBUG:requests_ntlm2.connection:> 'Proxy-Authorization: NTLM TlRMTVNTUAABAAAAMbCI4g4ADgAoAAAADwAPADYAAAAGAbEdAAAAD2F1dGhtaW5kLmxvY2FsRUMyQU1BWi1BMkJLNjBH\r\n'
DEBUG:requests_ntlm2.connection:> 'Proxy-Connection: Keep-Alive\r\n'
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 369, in connect
    self._tunnel()
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_ntlm2\connection.py", line 226, in _tunnel
    version, code, message, response = self._get_response()
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_ntlm2\connection.py", line 129, in _get_response
    version, code, message = response._read_status()
  File "\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ntlm_https.py", line 30, in <module>
    response = session.get('https://github.com')
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
```

what am I missing. I am able to work with http urls.

**Comment by dopstar** [comment]
@punnojoy sorry for replying so late.

Your proxy server does not support NTLM authentication

> INFO:requests_ntlm2.connection:< b'Proxy-Authenticate: Negotiate\r\n'

this ☝️ means that the proxy only supports `Negotiate` (aka `Kerberos`) authentication. 

If a proxy server supports NTLM authentication, it must have `'Proxy-Authenticate: NTLM\r\n'` header entry.

here is an example:
<img width="733" alt="0proxy" src="https://user-images.githubusercontent.com/2742870/165855116-12624647-16a4-4a98-9309-4bc9cb2c80fb.png">
