### ISSUE TITLE
failure through proxy with NTLM authentication

### ISSUE THREAD

**Issue by john997301** [dopstar/requests-ntlm2#9]
I'm stumbled on this and it looks promising.  However, I'm encountering an issue causing a traceback.

pip install requests-ntlm2
pip freeze
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
idna==2.8
ntlm-auth==1.4.0
pycparser==2.19
requests==2.22.0
requests-ntlm2==6.0.10
six==1.14.0
urllib3==1.25.8

test.py

```python
import urllib3
import requests
from requests_ntlm2 import HttpNtlmAdapter, HttpNtlmAuth

proxy = {
    'proxies': {
        'http': 'http://proxy.domain.com:8080',
        'https': 'http://proxy.domain.com:8080',
    },
    'auth': {
        'method': 'ntlm',
        'user': r'domain\user',
        'pass': 'ntlm_password'
    }
}

# random https site that doesn't need any auth
test_site = 'https://'


proxy_credential = proxy['auth']
proxy_user = proxy_credential['user']
proxy_password = proxy_credential['pass']
proxy_auth = HttpNtlmAuth(proxy_user, proxy_password)
proxy_adapter = HttpNtlmAdapter(proxy_user, proxy_password)

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

session = requests.Session()
session.proxies = proxy['proxies']
session.mount('https://', proxy_adapter)
session.mount('http://', proxy_adapter)
session.auth = proxy_auth


get_website = session.get(
    test_site,
    verify=False,
    timeout=(15, 30),
)

print(get_website)
```

`$ python test.py 
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    timeout=(15, 30),
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    self._tunnel()
  File "/projects/code/python/test-ntlm-proxy/lib/python3.7/site-packages/requests_ntlm2/connection.py", line 145, in _tunnel
    if line.lower().startswith("{}:".format(header)):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
`

Any help you can provide is greatly appreciated

**Comment by mchampanis** [comment]
i think line 145 in `connection.py`:

```
if line.lower().startswith("{}:".format(header)):
```

should be:

```
if line.decode("utf-8").lower().startswith("{}:".format(header)):
```

**Comment by arthurnalves** [comment]
> 
> 
> i think line 145 in `connection.py`:
> 
> ```
> if line.lower().startswith("{}:".format(header)):
> ```
> 
> should be:
> 
> ```
> if line.decode("utf-8").lower().startswith("{}:".format(header)):
> ```

I tried it and it didn't work =/
